version: "3"
services:
  frontend:
    image: "node:9.2"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/home/node/app
    expose:
      - 3000
    ports:
      - 8080:3000
    command: "npm start"
