version: "3"
services:
  frontend:
    build: ./app
    expose:
      - 3000
    volumes:
      - app_build:/usr/src/app/build
    depends_on:
      - server

  nginx:
    build: ./nginx
    depends_on:
      - frontend
    volumes:
      - app_build:/www
    links:
      - frontend
    ports:
      - "80:80"

  server:
    build: ./server
    expose:
      - 3000
    depends_on:
      - db

  db:
    image: "mongo:3.0"
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/var/log
    volumes:
      - ./data/db:/data/db
      - ./log/db:/var/log
    ports:
      - 27017
    command: mongod --smallfiles --logpath=/var/log/db.log

volumes:
  app_build:
