version: "3"
services:
  node:
    image: "node:9.2"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/home/node/app
    expose:
      - "3000"
    ports:
      - 8080:3000
    depends_on:
      - db
    command: "npm start"

  db:
    image: "mongo:3.0"
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/var/log
    volumes:
      - ./data/db:/data/db
      - ./log/db:/var/log
    ports:
      - 27017
    command: mongod --smallfiles --logpath=/var/log/db.log
