version: "3"
services:
  frontend:
    build: ./app
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: "mongo:3.0"
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/var/log
    volumes:
      - ./data/db:/data/db
      - ./log/db:/var/log
    ports:
      - 27017
    command: mongod --smallfiles --logpath=/var/log/db.log
